import { useCallback, useMemo, useState } from "react";
import { request } from "../lib/api";
import { useAccessToken } from "../lib/auth";
import { useApi } from "../lib/useApi";

type EtaPrecision = { dataAvailable: boolean; samples: number; within10MinutesPercent?: number; within15MinutesPercent?: number; within30MinutesPercent?: number; meanAbsoluteErrorMinutes?: number; message: string };
type ManagementSummary = {
  from: string; to: string; generatedAtUtc: string;
  headline: { orders: number; runs: number; completedRuns: number; runCompletionPercent?: number; plannedStops: number; completedStops: number; stopCompletionPercent?: number; measuredDeliveries: number; onTimeDeliveries: number; onTimeDeliveryPercent?: number; averageSiteDwellMinutes?: number; siteDelays: number; passThroughs: number; attentionRuns: number; attentionRatePercent?: number };
  efficiency: { allocatedRuns: number; allocationPercent?: number; assignedVehicles: number; activeVehicles: number; fleetUtilisationPercent?: number; assignedDrivers: number; activeDrivers: number; driverUtilisationPercent?: number; loadUtilisationPercent?: number; totalMiles: number; emptyMiles: number; emptyMilesPercent?: number };
  etaPrecision: EtaPrecision;
  customers: Array<{ customerCode: string; orders: number; deliveries: number; measuredDeliveries: number; onTimeDeliveries: number; onTimePercent?: number; averageDwellMinutes?: number; siteDelays: number }>;
  sites: Array<{ site: string; category?: string; visits: number; averageDwellMinutes?: number; maximumDwellMinutes?: number; waitLimitMinutes?: number; delays: number; delayRatePercent?: number }>;
  days: Array<{ date: string; runs: number; completedRuns: number; deliveries: number; measuredDeliveries: number; onTimePercent?: number; averageDwellMinutes?: number; siteDelays: number }>;
};

const iso = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const daysAgo = (days: number) => { const date = new Date(); date.setDate(date.getDate() - days); return iso(date); };
const pct = (value?: number) => value == null ? "—" : `${value.toFixed(1)}%`;
const mins = (value?: number) => value == null ? "—" : `${value.toFixed(1)} min`;
const num = (value?: number) => value == null ? "—" : new Intl.NumberFormat("en-GB", { maximumFractionDigits: 1 }).format(value);
const dateLabel = (value: string) => new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${value}T12:00:00`));
const csvCell = (value: unknown) => `"${(value == null ? "" : String(value)).replace(/"/g, '""')}"`;

function exportCsv(data: ManagementSummary, customers: ManagementSummary["customers"], eta: EtaPrecision) {
  const rows: unknown[][] = [["SLH TMS Management Report"], ["From", data.from, "To", data.to, "Generated", data.generatedAtUtc], [], ["Executive KPI", "Value"], ["Orders", data.headline.orders], ["Runs", data.headline.runs], ["Run completion %", data.headline.runCompletionPercent ?? ""], ["Stop completion %", data.headline.stopCompletionPercent ?? ""], ["On-time delivery %", data.headline.onTimeDeliveryPercent ?? ""], ["Average site dwell minutes", data.headline.averageSiteDwellMinutes ?? ""], ["Site delays", data.headline.siteDelays], ["Attention rate %", data.headline.attentionRatePercent ?? ""], ["Fleet utilisation %", data.efficiency.fleetUtilisationPercent ?? ""], ["Load utilisation %", data.efficiency.loadUtilisationPercent ?? ""], ["Empty miles %", data.efficiency.emptyMilesPercent ?? ""], ["ETA within 15 minutes %", eta.within15MinutesPercent ?? ""], ["ETA mean absolute error minutes", eta.meanAbsoluteErrorMinutes ?? ""], [], ["Daily performance"], ["Date", "Runs", "Completed runs", "Deliveries", "Measured deliveries", "On-time %", "Average dwell minutes", "Site delays"], ...data.days.map(day => [day.date, day.runs, day.completedRuns, day.deliveries, day.measuredDeliveries, day.onTimePercent ?? "", day.averageDwellMinutes ?? "", day.siteDelays]), [], ["Customer performance"], ["Customer", "Orders", "Deliveries", "Measured", "On time", "OTD %", "Average dwell", "Site delays"], ...customers.map(item => [item.customerCode, item.orders, item.deliveries, item.measuredDeliveries, item.onTimeDeliveries, item.onTimePercent ?? "", item.averageDwellMinutes ?? "", item.siteDelays]), [], ["Site performance"], ["Site", "Category", "Visits", "Average dwell", "Maximum dwell", "Wait limit", "Delays", "Delay rate %"], ...data.sites.map(item => [item.site, item.category ?? "", item.visits, item.averageDwellMinutes ?? "", item.maximumDwellMinutes ?? "", item.waitLimitMinutes ?? "", item.delays, item.delayRatePercent ?? ""])];
  const blob = new Blob([rows.map(row => row.map(csvCell).join(",")).join("\r\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `SLH-management-${data.from}-to-${data.to}.csv`; anchor.click(); URL.revokeObjectURL(url);
}

function Kpi({ label, value, detail, tone = "normal" }: { label: string; value: string; detail: string; tone?: "normal" | "good" | "attention" }) { return <article className={`management-kpi ${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>; }

export function Management() {
  const token = useAccessToken(); const [from, setFrom] = useState(daysAgo(6)); const [to, setTo] = useState(iso(new Date())); const [customer, setCustomer] = useState("All");
  const report = useApi(useCallback(async () => request<ManagementSummary>(`/api/v1/management/resilient-summary?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`, await token(), undefined, 40000), [from, to, token]));
  const precision = useApi(useCallback(async () => request<EtaPrecision>(`/api/v1/management/eta-precision?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`, await token(), undefined, 40000), [from, to, token]));
  const eta = precision.data || report.data?.etaPrecision; const customerOptions = useMemo(() => ["All", ...(report.data?.customers.map(item => item.customerCode) || [])], [report.data]); const customers = useMemo(() => customer === "All" ? (report.data?.customers || []) : (report.data?.customers || []).filter(item => item.customerCode === customer), [customer, report.data]);
  const applyPreset = (days: number) => { setTo(iso(new Date())); setFrom(daysAgo(days - 1)); }; const refreshAll = () => { void report.refresh(); void precision.refresh(); };
  return <section className="management-page"><div className="management-heading"><div><p className="eyebrow">Management intelligence</p><h1>Transport performance</h1><p>One management view built from planned work, live operations and confirmed geofence activity.</p></div><div className="management-actions no-print"><button onClick={() => report.data && eta && exportCsv(report.data, customers, eta)} disabled={!report.data || !eta}>Export CSV</button><button onClick={() => window.print()} disabled={!report.data}>Print / PDF</button></div></div>
  <div className="management-filters no-print"><div className="management-presets"><button onClick={() => applyPreset(1)}>Today</button><button onClick={() => applyPreset(7)}>7 days</button><button onClick={() => applyPreset(30)}>30 days</button></div><label>From<input type="date" value={from} onChange={event => setFrom(event.target.value)} /></label><label>To<input type="date" value={to} onChange={event => setTo(event.target.value)} /></label><label>Customer<select value={customer} onChange={event => setCustomer(event.target.value)}>{customerOptions.map(option => <option key={option}>{option}</option>)}</select></label><button className="primary" onClick={refreshAll}>Refresh</button></div>
  {report.loading && <div className="state">Calculating management KPIs…</div>}{report.error && <div className="state error">{report.error}</div>}{report.data && <><div className="management-period">Reporting period <strong>{dateLabel(report.data.from)} – {dateLabel(report.data.to)}</strong><span>Generated {new Date(report.data.generatedAtUtc).toLocaleString("en-GB")}</span></div><div className="management-kpis"><Kpi label="On-time delivery" value={pct(report.data.headline.onTimeDeliveryPercent)} detail={`${report.data.headline.onTimeDeliveries}/${report.data.headline.measuredDeliveries} measured deliveries`} tone={(report.data.headline.onTimeDeliveryPercent ?? 100) < 90 ? "attention" : "good"} /><Kpi label="Run completion" value={pct(report.data.headline.runCompletionPercent)} detail={`${report.data.headline.completedRuns}/${report.data.headline.runs} runs complete`} /><Kpi label="Stop completion" value={pct(report.data.headline.stopCompletionPercent)} detail={`${report.data.headline.completedStops}/${report.data.headline.plannedStops} planned stops`} /><Kpi label="Average site dwell" value={mins(report.data.headline.averageSiteDwellMinutes)} detail={`${report.data.headline.siteDelays} site delay events`} tone={report.data.headline.siteDelays > 0 ? "attention" : "normal"} /><Kpi label="Fleet utilisation" value={pct(report.data.efficiency.fleetUtilisationPercent)} detail={`${report.data.efficiency.assignedVehicles}/${report.data.efficiency.activeVehicles} active vehicles used`} /><Kpi label="Load utilisation" value={pct(report.data.efficiency.loadUtilisationPercent)} detail="Pallet spaces used vs available" /><Kpi label="Empty mileage" value={pct(report.data.efficiency.emptyMilesPercent)} detail={`${num(report.data.efficiency.emptyMiles)} of ${num(report.data.efficiency.totalMiles)} miles`} /><Kpi label="Runs needing attention" value={pct(report.data.headline.attentionRatePercent)} detail={`${report.data.headline.attentionRuns} runs with an exception signal`} tone={report.data.headline.attentionRuns > 0 ? "attention" : "good"} /></div>
  <section className="management-panel eta-panel"><div><p className="eyebrow">ETA precision</p><h2>{eta?.dataAvailable ? pct(eta.within15MinutesPercent) : "Collecting ETA samples"}</h2><p>{precision.error || eta?.message || "ETA precision is loading."}</p></div><div className="eta-precision-grid"><article><span>Within ±10m</span><strong>{pct(eta?.within10MinutesPercent)}</strong></article><article><span>Within ±15m</span><strong>{pct(eta?.within15MinutesPercent)}</strong></article><article><span>Within ±30m</span><strong>{pct(eta?.within30MinutesPercent)}</strong></article><article><span>Mean error</span><strong>{mins(eta?.meanAbsoluteErrorMinutes)}</strong></article></div></section>
  <div className="management-two-column"><section className="management-panel"><p className="eyebrow">Operational efficiency</p><h2>Plan & fleet utilisation</h2><div className="management-stat-list"><div><span>Runs allocated</span><strong>{pct(report.data.efficiency.allocationPercent)}</strong><small>{report.data.efficiency.allocatedRuns}/{report.data.headline.runs}</small></div><div><span>Drivers used</span><strong>{pct(report.data.efficiency.driverUtilisationPercent)}</strong><small>{report.data.efficiency.assignedDrivers}/{report.data.efficiency.activeDrivers}</small></div><div><span>Pass-through geofences</span><strong>{report.data.headline.passThroughs}</strong><small>Review missed/short visits</small></div><div><span>Orders in period</span><strong>{report.data.headline.orders}</strong><small>Planned and operational records</small></div></div></section><section className="management-panel"><p className="eyebrow">Exception pressure</p><h2>Where management time is going</h2><div className="management-stat-list"><div><span>Runs needing attention</span><strong>{report.data.headline.attentionRuns}</strong><small>Allocation, mapping or operational signal</small></div><div><span>Site delay events</span><strong>{report.data.headline.siteDelays}</strong><small>Exceeded configured wait threshold</small></div><div><span>Measured service calls</span><strong>{report.data.headline.measuredDeliveries}</strong><small>Booking window + actual arrival</small></div><div><span>ETA samples scored</span><strong>{eta?.samples ?? 0}</strong><small>Live prediction vs confirmed arrival</small></div></div></section></div>
  <section className="management-panel"><div className="management-section-heading"><div><p className="eyebrow">Trend</p><h2>Daily performance</h2></div></div><div className="management-table-wrap"><table className="management-table"><thead><tr><th>Date</th><th>Runs</th><th>Completed</th><th>Deliveries</th><th>OTD</th><th>Avg dwell</th><th>Site delays</th></tr></thead><tbody>{report.data.days.map(day => <tr key={day.date}><td>{dateLabel(day.date)}</td><td>{day.runs}</td><td>{day.completedRuns}</td><td>{day.deliveries}</td><td><span className={(day.onTimePercent ?? 100) < 90 ? "metric-bad" : "metric-good"}>{pct(day.onTimePercent)}</span></td><td>{mins(day.averageDwellMinutes)}</td><td>{day.siteDelays}</td></tr>)}</tbody></table></div></section>
  <section className="management-panel"><div className="management-section-heading"><div><p className="eyebrow">Customer service</p><h2>Performance by customer</h2></div><small>{customer === "All" ? "All customers" : customer}</small></div><div className="management-table-wrap"><table className="management-table"><thead><tr><th>Customer</th><th>Orders</th><th>Deliveries</th><th>Measured</th><th>On time</th><th>OTD</th><th>Avg dwell</th><th>Delays</th></tr></thead><tbody>{customers.map(item => <tr key={item.customerCode}><td><strong>{item.customerCode}</strong></td><td>{item.orders}</td><td>{item.deliveries}</td><td>{item.measuredDeliveries}</td><td>{item.onTimeDeliveries}</td><td><span className={(item.onTimePercent ?? 100) < 90 ? "metric-bad" : "metric-good"}>{pct(item.onTimePercent)}</span></td><td>{mins(item.averageDwellMinutes)}</td><td>{item.siteDelays}</td></tr>)}</tbody></table></div></section>
  <section className="management-panel"><div className="management-section-heading"><div><p className="eyebrow">Site intelligence</p><h2>Dwell & delay by site</h2></div><small>Worst delay exposure sorted first</small></div><div className="management-table-wrap"><table className="management-table"><thead><tr><th>Site</th><th>Type</th><th>Visits</th><th>Avg dwell</th><th>Max dwell</th><th>Limit</th><th>Delays</th><th>Delay rate</th></tr></thead><tbody>{report.data.sites.map(item => <tr key={item.site}><td><strong>{item.site}</strong></td><td>{item.category || "—"}</td><td>{item.visits}</td><td>{mins(item.averageDwellMinutes)}</td><td>{mins(item.maximumDwellMinutes)}</td><td>{mins(item.waitLimitMinutes)}</td><td>{item.delays}</td><td><span className={(item.delayRatePercent ?? 0) > 10 ? "metric-bad" : ""}>{pct(item.delayRatePercent)}</span></td></tr>)}</tbody></table></div></section></>}</section>;
}
