import { useState } from 'react';
import { useIsAuthenticated, useMsal } from '@azure/msal-react';
import { BrowserRouter, NavLink, Route, Routes } from 'react-router-dom';
import { Dashboard, Exceptions, ExportCentre, LiveTracking, Loads, MasterData, OperationalPlaceholder, Orders, PlanningBoard, Reporting, StagingQueue } from './pages/Pages';
import { apiScope } from './lib/auth';

const navigation = [['/', 'Planner'], ['/dashboard', 'Operations dashboard'], ['/order-intake', 'Order entry'], ['/loads', 'Loads'], ['/allocation', 'Allocation'], ['/tracking', 'Live tracking'], ['/staging', 'Staging review'], ['/exceptions', 'Exceptions'], ['/master-data', 'Master data & CRM'], ['/reporting', 'Reporting'], ['/exports', 'Exports'], ['/admin', 'Admin']];

function Shell() {
  const authenticated = useIsAuthenticated(); const { instance, accounts } = useMsal(); const [open, setOpen] = useState(false);
  const signIn = () => instance.loginRedirect({ scopes: apiScope ? [apiScope] : [] });
  return <div className="app-shell"><header><button className="menu" onClick={() => setOpen(!open)} aria-label="Toggle navigation">☰</button><NavLink className="brand" to="/"><span>SLH</span><small>Operations planner</small></NavLink><div className="header-context"><b>Today’s transport plan</b><small>Control loads, drivers and exceptions</small></div><div className="header-actions">{authenticated ? <><span className="user">{accounts[0]?.name}</span><button onClick={() => instance.logoutRedirect()}>Sign out</button></> : <button className="primary" onClick={signIn} disabled={!apiScope}>Sign in with Microsoft</button>}</div></header><aside className={open ? 'open' : ''}><NavLink className="new-order" to="/order-intake" onClick={() => setOpen(false)}>＋ New order</NavLink><div className="nav-title">Daily control</div>{navigation.slice(0, 6).map(([path, label]) => <NavLink key={path} to={path} end={path === '/'} onClick={() => setOpen(false)}>{label}</NavLink>)}<div className="nav-title">Setup & insight</div>{navigation.slice(6).map(([path, label]) => <NavLink key={path} to={path} end={path === '/'} onClick={() => setOpen(false)}>{label}</NavLink>)}</aside><main>{!authenticated && <div className="notice">Sign in with Microsoft to see live operations data.</div>}<Routes><Route path="/" element={<PlanningBoard />} /><Route path="/dashboard" element={<Dashboard />} /><Route path="/order-intake" element={<Orders />} /><Route path="/loads" element={<Loads />} /><Route path="/allocation" element={<PlanningBoard />} /><Route path="/tracking" element={<LiveTracking />} /><Route path="/staging" element={<StagingQueue />} /><Route path="/exceptions" element={<Exceptions />} /><Route path="/reporting" element={<Reporting />} /><Route path="/exports" element={<ExportCentre />} /><Route path="/master-data" element={<MasterData />} />{navigation.slice(1).filter(([path]) => !['/dashboard', '/order-intake', '/loads', '/allocation', '/tracking', '/staging', '/exceptions', '/reporting', '/exports', '/master-data'].includes(path)).map(([path, label]) => <Route key={path} path={path} element={<OperationalPlaceholder title={label} />} />)}</Routes></main></div>;
}
export function App() { return <BrowserRouter><Shell /></BrowserRouter>; }
