name: Trigger auto deployment for slh-tms-portal-prod

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/slh-tms-portal-prod-AutoDeployTrigger-9ef45802-17f2-425d-9502-8db65f35c937.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: b40a6b9e-69f8-4861-8e61-e61410127359
          tenant-id: 5aec48a1-c3c7-4cfd-a073-b38ae50041b1
          subscription-id: 29d5b52a-5b9f-4b5a-9495-892f1c2a30f3

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: slhtmsacrprod.azurecr.io
          registryUsername: ${{ secrets.SLHTMSPORTALPROD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SLHTMSPORTALPROD_REGISTRY_PASSWORD }}
          containerAppName: slh-tms-portal-prod
          resourceGroup: slh-tms-prod-rg
          imageToBuild: slhtmsacrprod.azurecr.io/slh-tms-portal-prod:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


